"""first migration

Revision ID: 0265d5bd821e
Revises:
Create Date: 2023-08-05 14:56:44.096471

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0265d5bd821e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
                    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
                    sa.Column('title', sa.String(length=60), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('submenu',
                    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
                    sa.Column('title', sa.String(length=60), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('menu_id', sa.UUID(as_uuid=False), nullable=False),
                    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dish',
                    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
                    sa.Column('title', sa.String(length=60), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('submenu_id', sa.UUID(as_uuid=False), nullable=False),
                    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###
