"""update migrate

Revision ID: 56f8cca74054
Revises: f3b91c108478
Create Date: 2023-07-22 13:21:22.133762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f8cca74054'
down_revision = 'f3b91c108478'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sub_menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_menu_id'], ['submenu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dishes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sub_menu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sub_menu_id'], ['submenu.id'], name='dishes_sub_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dishes_pkey')
    )
    op.drop_table('dish')
    # ### end Alembic commands ###
