"""update migration

Revision ID: d314bc7dddd2
Revises: 56f8cca74054
Create Date: 2023-07-23 18:16:10.181872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd314bc7dddd2'
down_revision = '56f8cca74054'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu_id', sa.Integer(), nullable=False))
    op.drop_constraint('dish_sub_menu_id_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu_id'], ['id'])
    op.drop_column('dish', 'sub_menu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('sub_menu_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_sub_menu_id_fkey', 'dish', 'submenu', ['sub_menu_id'], ['id'])
    op.drop_column('dish', 'submenu_id')
    # ### end Alembic commands ###
