version: '3.8'

services:

  db:
    container_name: fastapi_db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 100

  cache:
    container_name: fastapi_cache
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 200

  app:
    container_name: fastapi_app
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
      - cache
    env_file:
      - .env
    ports:
      - 8000:8000
    command: bash -c './prestart.sh && uvicorn src.main:app --host 0.0.0.0'
