version: '3.8'

services:

  db:
    container_name: tests_db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 10s
      retries: 100

  cache:
    container_name: fastapi_cache
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 200

  test_app:
    container_name: tests_app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/tests-reports:/app/tests-reports
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c './test-start.sh'
