version: '3'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    command: bash -c './prestart.sh && uvicorn src.main:app --host 0.0.0.0'
